import type { AdAccount } from '@/types';

export const PLACEHOLDER_ACCOUNTS: AdAccount[] = [
  { id: 'ph1', platform: 'META', category: 'ad-accounts', profileName: 'US Meta Agency Account', country: 'US', countryFlag: '🇺🇸', spendingLimit: 50000, ageMonths: 24, price: 149, status: 'AVAILABLE', features: ['Credit Line', 'Uncapped', 'Verified BM', 'Agency'], description: 'High-trust US Meta agency account with $50K spend history, fully warmed and ready to scale.', isFeatured: true, createdAt: '' },
  { id: 'ph2', platform: 'GOOGLE', category: 'ad-accounts', profileName: 'Google Ads MCC Account', country: 'UK', countryFlag: '🇬🇧', spendingLimit: 100000, ageMonths: 36, price: 299, status: 'AVAILABLE', features: ['MCC Access', 'Clean History', 'High Limit', '3yr Aged'], description: 'Premium Google Ads MCC with £100K spend limit and 3 years of clean ad history.', isFeatured: true, createdAt: '' },
  { id: 'ph3', platform: 'TIKTOK', category: 'ad-accounts', profileName: 'TikTok Business Center', country: 'SG', countryFlag: '🇸🇬', spendingLimit: 30000, ageMonths: 12, price: 89, status: 'AVAILABLE', features: ['Pixel Ready', 'Verified', 'SEA Region'], description: 'TikTok Business Center account with verified merchant status for South East Asia region.', isFeatured: false, createdAt: '' },
  { id: 'ph4', platform: 'META', category: 'profiles', profileName: 'High-Trust FB Profile US', country: 'US', countryFlag: '🇺🇸', spendingLimit: null, ageMonths: 48, price: 45, status: 'AVAILABLE', features: ['Friends Seeded', 'OG Account', 'US IP History'], description: 'Organic US Facebook profile aged 4 years with natural activity history.', isFeatured: false, createdAt: '' },
  { id: 'ph5', platform: 'META', category: 'bm-verified', profileName: 'Verified BM — Corporate Tier', country: 'AE', countryFlag: '🇦🇪', spendingLimit: 200000, ageMonths: 18, price: 499, status: 'AVAILABLE', features: ['Corporate Verified', 'UAE Entity', '$200K Spend Cap', 'Whitelisted'], description: 'Corporate-tier Verified Business Manager from UAE entity with $200K monthly spend allocation.', isFeatured: true, createdAt: '' },
  { id: 'ph6', platform: 'BING', category: 'ad-accounts', profileName: 'Bing Ads Aged Account', country: 'CA', countryFlag: '🇨🇦', spendingLimit: 25000, ageMonths: 20, price: 65, status: 'AVAILABLE', features: ['CAD Billing', 'Clean History', 'Aged 20m'], description: 'Aged Canadian Bing Ads account with CAD billing and $25K spend history.', isFeatured: false, createdAt: '' },
];
